### PR TITLE
Russell

### PR DESCRIPTION
**Pull request by russellpekala**
added to credits

### CODE REVIEW

**Comment by russellpekala** [comment]
Hopefully this worked?

**Comment by UlyssesInvictus** [comment]
Still have to resolve conflicts. See the "command line instructions" link and do those.

**Comment by russellpekala** [comment]
I can't figure this out :(

**Comment by UlyssesInvictus** [comment]
okay ignore whatever github tells you and do this

1. go to your command line
2. make sure the master branch is up to date (git checkout master; git pull)
3. switch to your branch (git checkout russell)
4. run `git merge master` to merge in master
5. resolve conflicts in code, commit, and push (git push)
 
Come back here and make sure it lets your merge now.

**Comment by russellpekala** [comment]
It's giving me this error: 
Russells-MacBook-Air:credits pekala$ git pull
Updating 0048ce9..a34b649
fatal: Unable to create '/Users/RussellPekala/Desktop/Datamatch-Archives/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manualRusseRusRusRuRRuRRRusRRRuRusseRusRuRRussells-MacBook-Air:credits pekala$

**Comment by russellpekala** [comment]
I might just start all the way over (wipe out things on my local directory, reclone the thing).  This project is going to make me fear git for the rest of my life.

**Comment by UlyssesInvictus** [comment]
Oi voy, that's not a regular git error, it means something totally messed up earlier, maybe you were pulling and closed your laptop in the middle, or you just left a hanging merge and git is just super confused right now.

Rather than totally troubleshoot, I'm going to recommend you nuke the folder, reclone, then start over by making a new branch and PR. (This should be mostly fine, given that you have so little to change.) Correspondingly, I'm closing this PR since you should be making a new one.

**Comment by russellpekala** [comment]
Okay sounds good we were thinking the same thing

**Pull request closed without merging**
